package com.cinerama.backend.exception;

public enum ErrorCode {
    USER_NOT_FOUND,
    INVALID_TOKEN,
    INVALID_ARGUMENT,
    CONFLICT,
    VALIDATION_ERROR,
    CONSTRAINT_VIOLATION,
    ACCESS_DENIED,
    INTERNAL_ERROR,
    TOKEN_NOT_BELONG_USER,
    EXPIRED_TOKEN,
    PASSWORDS_NOT_MATCH,
    UNAUTHORIZED,
    UNKNOWN_ERROR
}