version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - /c/Users/Usuario/Desktop/Cinerama/backend/src/main/resources/templates/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3200:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_LIVE_ENABLED=false
    volumes:
      - ./src/main/resources/templates/monitoring/dashboards:/etc/grafana/dashboards
      - ./src/main/resources/templates/monitoring/provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring

volumes:
  grafana-storage:

networks:
  monitoring:
